# Generated by Django 4.2.9 on 2024-02-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
