# Generated by Django 4.2.9 on 2024-08-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delete_person"),
        ("accounts", "0002_friendship"),
    ]

    operations = []
